eoscostarica/guias.eoscostarica.io

- docs/recursos-visuales/material-ui.md
- website/static/css/custom.css
- fix: fix broken logos links and update docs
closes #12
> fix: update docs and fix broken links

- website/pages/en/index.js
- website/siteConfig.js
- fix&feat: add collapsible menu option & clean home page
- fix: update docs and fix broken links
- fix: fix broken logos links
closes #14 #15
> add collapsible menu option and clean home page

- README.md
- website/package-lock.json
Este update se realizo con la intensión de añadir un tutorial de como ejecutar la plataforma de manera local desde Windows 10
#28 
1.Seguir el tutorial paso a paso sin saltar alguno.
> docs(README): se añade un tutorial donde se definen los pasos a seguir para correr el sitio de forma local desde windows 10

- docs/aprender-eosio/uso-de-recursos.md
- website/sidebars.json
Update docs with new content about resources from LatamLink
#30 
1. Unfold the `Aprender EOSIO` tab
1. Look the content on the `Uso de recursos` tab
> Update docs 

- docs/aprender-eosio/uso-de-recursos.md
#43 
fix code block style in [this page](https://desarrolladores.eoscostarica.io/docs/aprender-eosio/uso-de-recursos)
1. Unfold the `Aprender EOSIO` tab
1. Look the content on the `Uso de recursos` tab
> add code block style 

- docs/aprender-eosio/contrato-hola-mundo.md
- docs/aprender-eosio/cuentas-permisos.md
- docs/aprender-eosio/funciones-importantes.md
- docs/aprender-eosio/librerias-sdk.md
- docs/aprender-eosio/protocolo-eosio.md
- website/sidebars.json
#33 
#35 
#37 
#39 
#41 
1. Run local proyect
1. Go to Aprender EOSIO
> docs(new docs):Create docs in aprender eosio

- README.md
- docs/aprender-eosio/como-iniciar.md
- docs/aprender-eosio/contrato-hola-mundo.md
- docs/aprender-eosio/llaves-privadas.md
- docs/aprender-eosio/protocolo-eosio.md
- docs/proyectos-de-codigo-abierto.md
- website/siteConfig.js
1. Go to learn.eoscostarica.io 301 redirect should point you to guide.eoscostarica.io
1. Go to developers.eoscostarica.io 301 redirect should point you to guide.eoscostarica.io
> change site config domain name

- .github/workflows/nodejs.yml
> update repo name

- website/sidebars.json
- website/siteConfig.js
#52 
1. Run local project
1. See nav bar
> conf(sidebars.json): add Aprender EOSIO and English

- docs/aprender-eosio/redes-eosio.md
- website/sidebars.json
#57
1. Run local project 
1. Go to Aprender EOSIO
> docs(redes-eosio): create new doc

- website/siteConfig.js
#20 
- Add google analytics `UA-173987-66` track ID in `siteConfig`
> add google analytics integration

- website/siteConfig.js
@JeanVegaD  estaba probando el google analytics pero no me esta registrado trafico , creo que mejor deshabilitamos el  tag manager y volvemos a probar. 
1.
1.
1.
> Disable Google Tag Manager

- docs/aprender-eosio/cadena-de-bloques-eos.md
- docs/aprender-eosio/contratos-inteligentes.md
- docs/aprender-eosio/cpp-moderno.md
- docs/aprender-eosio/cuentas-permisos.md
- docs/aprender-eosio/desarrollo-de-dapps.md
- docs/aprender-eosio/devops.md
- docs/aprender-eosio/funciones-importantes.md
- docs/aprender-eosio/mecanismo-de-consenso.md
- docs/aprender-eosio/protocolo-eosio.md
- docs/aprender-eosio/redes-eosio.md
- docs/aprender-eosio/software-eosio.md
- docs/aprender-eosio/uso-de-recursos.md
- website/sidebars.json
re-arrange videos #58 
**`Productor de Bloques`**
1.  Move the content to `Mecanismos de consenso`
1. Delete `Productor de Bloques` page
**`DevOps`**
1. Delete broken links
**`Cadena de bloques EOS`**
1. Delete broken links
1. Move "Brief introduction to c++" video to `c++ moderno` 
1. Move "Basic EOSIO smart contract schema...." video to `contratos inteligentes`
1. Delete duplicate content from  `contratos inteligentes`
1. Add link to `contratos inteligentes` page
**`Software EOS`** 
1. Move the video to `cuentas y permisos`
1. Move "Delegated Proof of Stake (DPoS)"  information to `mecanismos de concenso`
1. Delete `Software EOS` page
1. Look the content in "Aprender EOSIO" tab
> Re arrange videos

- docs/comunidad/canales-de-telegram.md
- website/sidebars.json
> telegram channels

- website/siteConfig.js
> files(siteConfig.js): add algolia integration

- docs/herramientas-para-desarrolladores.md
#70 
1. Run project locally.
1. Go to Nuestras Herramientas Favoritas
> docs(herramientas-para-desarroladores.md): update content

- docs/recursos-visuales/logos-de-lifebank.md
- website/sidebars.json
> update visual resources

- docs/proyectos-de-codigo-abierto.md
[Issue 70](https://github.com/eoscostarica/guide.eoscostarica.io/issues/70)
> Add NPM packages page

- docs/proyectos-de-codigo-abierto.md
> fix broken links

- docs/material-ui.md
- docs/recursos-visuales.md
- website/sidebars.json
> update Material UI Theme

- docs/aprender-eosio/tutorial-flujo-trabajo-git.md
- website/sidebars.json
> docs(tutorial-flujo-trabajo-git): add document

- docs/comunidad/canales-de-telegram.md
#86 
1. Go to canales de telegram
> docs(canales-telegram): update content

- docs/metodologias-agiles.md
- website/sidebars.json
#22 
1. Run project locally.
1. Go guías generales and metodologías ágiles. 
1.
> docs(metodologias-agiles): create doc metodologias-agiles

- website/docs/herramientas/explorador-de-bloques.md
> docs: remove broken links

- website/docusaurus.config.js
#98 
1. Ruyn project locally.
1. View footer to home page
> docs(docusaurus.config.js):Fix text to footer

- website/docs/aprender-eosio/contratos-ricardianos.md
- website/sidebars.js
#96 
1. Go to aprender eosio and contratos ricardianos
> docs(contratos-ricardianos.md):create contratos-ricardianos

- website/docusaurus.config.js
> feat: edit button

- website/docs/comunidad/redes-sociales.md
- website/sidebars.js
> docs: social media guidelines 

- website/package.json
````
Module not found: Error: Can't resolve '@material-ui/core/CardMedia' in '/home/runner/work/guias.eoscostarica.io/guias.eoscostarica.io/website/src/pages'
````
> fix build error

- website/docs/herramientas/opciones-configuracion-nodeos.md
- website/sidebars.js
> docs: nodeos command line reference

- website/src/pages/index.js
> fix(index); update wrong link

- website/docs/aprender-eosio/cadena-de-bloques-eos.md
- website/docs/aprender-eosio/cpp-moderno.md
- website/docs/aprender-eosio/devops.md
- website/docs/herramientas-para-desarrolladores.md
- website/sidebars.js
> style: check styles

- website/docs/metodologias-agiles.md
- website/sidebars.js
> docs(metodologias-agiles.md): create new site

- README.md
- docs/material-ui.md
- docs/proyectos-de-codigo-abierto.md
- docusaurus.config.js
- package.json
- sidebars.js
- src/pages/index.js
- Fix broken image links
- Add dir descriptions to readme
- Update Docusaurus version
- Prettify `sidebars.js`
> Update image paths and update docusaurus

- docs/metodologias-agiles.md
> docs(metodologias-agiles.md): fix format to videos

- docs/aprender-eosio/tutorial-flujo-trabajo-git.md
- sidebars.js
#131 
#Detalis 
Add new page for flujo de trabajo de Git in tutoriales
> docs(tutorial-flujo-trabajo-git.md): add new page consolide content to RP english

- docs/comunidad/canales-de-telegram.md
- docs/comunidad/redes-eosio.md
- docs/comunidad/redes-sociales.md
> Updating and consolide content

- docs/aprender-eosio/cadena-de-bloques-eos.md
- docs/aprender-eosio/cadenas-hermanas-de-eos.md
- docs/aprender-eosio/contrato-hola-mundo.md
- docs/aprender-eosio/contratos-inteligentes.md
- docs/aprender-eosio/cpp-moderno.md
- docs/aprender-eosio/cuentas-permisos.md
- docs/aprender-eosio/desarrollo-de-dapps.md
- docs/aprender-eosio/devops.md
- docs/aprender-eosio/mecanismo-de-consenso.md
- docs/aprender-eosio/productor-de-bloques.md
- docs/aprender-eosio/uso-de-recursos.md
> fix: update embedded videos

- docs/comunidad/publicaciones-blog.md
- sidebars.js
#133 
Add pague publicaciones blog to comunidad
> docs(publicaciones-blog.md): create new page to blog posts in comunidad

- docs/proyectos-de-codigo-abierto.md
- sidebars.js
1. Correct Evodex Link
1. Re organize sidebar items
> add evodex website

- docs/herramientas/librerias-sdk.md
- docs/plantilla-para-backend.md
- This PR fixes build error due to broken link 
- removed extra content from backend boilerplate page
- added links to SDK libraries 
No issue exists
1. yarn start
1. go to SDK page under tools
> fix(backend boilerplate): fix broken link build error

- package.json
Update to version 2.0.0-alpha.62
> feat(docusaurus): Update to version 2.0.0-alpha.62

- docusaurus.config.js
- src/css/custom.css
> fix: remove version badge

- package.json
> feat(docusaurus): Update docusaurus version to alpha-70

- docs/comunidad/enlaces-utiles.md
- sidebars.js
Resolves #169  
1. Go to Enlaces Útiles inside of Comunidad tag
1. Check content is righ
> feat(docs): useful links spanish version

- docs/herramientas/preguntas-frecuentes.md
- sidebars.js
Resolves #161 
1. Check content
1. Check grammar
1. Check content is inside of tool section
> feat(frontend): sección de preguntas frecuentes

- docs/aprender-eosio/contratos-inteligentes.md
- docs/devops.md
- docs/herramientas/explorador-de-bloques.md
- docs/plantilla-para-backend.md
- docs/tutoriales/contrato-hola-mundo.md
Resolves #180  
1.Check links is right
> fix(frontend): fix-broken-links

- src/theme/Footer/index.js
- src/theme/Footer/styles.module.css
Resolves #198 
1. Check footer logo is total visible in dark mode
> fix(frontend): fix footer logo dark theme

- docs/aprender-eosio/uso-de-recursos.md
- docs/comunidad/publicaciones-blog.md
- docs/pautas-para-codigo-abierto.md
- docs/plantilla-para-aplicacion-web.md
- docs/plantilla-para-backend.md
- docs/plantilla-readme.md
- docs/redes-sociales.md
- docs/tutoriales/tutorial-flujo-trabajo-git.md
Resolves #207 
1. Check Sidebar
> fix(sidebar): Capital letters-sidebar

- docs/devops.md
Resolves #206  
1. Go to DevOps
1. Check content
> update(devops): Add new content

- docs/tutoriales/llaves-github.md
- sidebars.js
Resolves #214  
1. Go to Llaves de GitHub
1. Check Content
> feat(tutoriales): new llaves de github section

- docs/tutoriales/guia-github.md
Resolves #225 
1. Go to Tutoriales/Guía GitHub
2. Check content is right.
> docs(frontend): update GitHub Guide

- docs/devops.md
Resolves #227  
1. Fix Image Devops
> fix(image): update image

- docs/plantilla-readme-codigo-fuente.md
Resolves #236 
1. Check content is right
> fix(content): Update readme source code

- docs/comunidad/enlaces-utiles.md
Resolves #243
1. Check Useful Links
> update(useful-links):add new links

- docs/tutoriales/graphql.md
- sidebars.js
Resolves #231 
1. Check new content
1. Check is inside of tutorials
> feat(documentation): add graphql content

- docs/herramientas-para-desarrolladores.md
Resolves #254 
1. Go to Nuestras herramientas favoritas
> docs(frontend): Add Vault in favorite tools

- docusaurus.config.js
> fix(webapp): change lang tag

- docs/tutoriales/instalacion-de-red-privada.md
closes #265  
1. `yarn start`
2. Go to `http://localhost:3000` and see the updated tutorial
> docs: update private network tutorial

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Se tradujeron las plantillas reportadas en la issue #173
> se tradujeron plantillas para tiquetes

- docs/tutoriales/instalacion-de-nodos.md
> docs: node tutorial

- docs/proyectos-de-codigo-abierto.md
> docs: add ggoods to os projects

- docs/comunidad/enlaces-utiles.md
> docs: add EOSCommunity.org Forums to useful links

- docs/proyectos-de-codigo-abierto.md
> update dashboard url

- docs/aprender-eosio/desarrollo-de-dapps.md
1. Resuelve #369 
1. Corre `yarn start`
2. Ir a `localhost:3000`
3. Ir a Pautas para Desarrolladores > Blockchain EOSIO > Desarrollo de Dapps
> (docs): fix broken links

- docs/tutoriales/guia-markdown.md
#280
1. Corre `yarn start`
2. Ir a `localhost:3000`
3. Ir a Pautas para Desarrolladores > Tutoriales > Guia Markdown
> (docs): mejora sintaxis guia markdown

- docs/aprender-eosio/seguridad-blockchain.md
#360
1. Correr `yarn start`
2. Ir a `localhost:3000`
3. Ir a Pautas para Desarrolladores > Blockchain EOSIO > Seguridad
> (docs): agregar intro al video de seguridad blockchain

- docs/aprender-eosio/nft-en-eosio.mdx
1. Correr `yarn build`
2. Correr `yarn serve`
3. Ir a `localhost:3000`
4. Ir a Pautas para Desarrolladores > Aprende EOSIO > NFTs en el ecosistema de EOSIO
> (docs): code review fix translation

- docs/metodologia-vuelos.md
- sidebars.js
> Flight methodology doc

- docusaurus.config.js
- package.json
- src/pages/index.js
- src/theme/Footer/index.js
- yarn.lock
Update the old dependencies without breaking changes
- resolves #312 
1.Move between parts of the guide
> 312 update project dependencies

- docs/aprender-eosio/mecanismo-de-consenso.md
- docs/herramientas/pow-vs-pos-vs-dpos.md
- sidebars.js
- resolves #318 
1.Go to Aprender EOSIO
2.Go to Mecanismos de consenso
> pow vs pos vs dpos #318

- docs/aprender-eosio/migracion-mandel.md
- docs/aprender-eosio/protocolo-eosio.md
- sidebars.js
- resolves #319
1. Go to "Aprender EOSIO"
2. Open "Protocolo EOSIO"
3. Check the content
4. Go to the sidebar and open "Migración de EOSIO a Mandel"
5. Check the content
> Add EOS, EOSIO and Mandel information

- docs/mecanismos-de-consenso-blockchain.md
- sidebars.js
- resolves #480
1. Go to Developer Guidelines
2. Go to Consensus Mechanisms Blockchain
> feat(common): Adding above consensus mechanisms

- docs/pautas-para-codigo-abierto.md
- resolves #474 
1. Go to "Guías generales" or "Pautas para Desarrolladores" 
2. Open "Pautas para Código Abierto"
3. Check the new content in "Convención para los Nombres de las Ramas"
> feat(open-source-guidelines): Add branch naming convention

- docs/devops.md
- docs/herramientas-para-desarrolladores.md
- docs/metodologias-agiles.md
- docs/recursos-visuales.md
- docs/tutoriales/cpp-moderno.md
- src/pages/index.js
- src/theme/Footer/index.js
- resolves #[299](https://github.com/eoscostarica/guide.eoscostarica.io/issues/299)
- For markdown images since Docusaurus [v2.0.0-beta.16](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.16) they are lazy-loaded
- Add loading lazily in pages with many images or embedded videos 
1. Check that the changes are correct
> perf: Add lazy loading

- docs/aprender-eosio/fundacion-red-eos.md
- sidebars.js
- resolves #385
1. Go to Aprender EOSIO
2. Go to Blue Papers
> feat(frontend): Add information about Blue Papers #385

- docusaurus.config.js
- src/pages/index.js
- resolves #424
1. See the changes in homepage
> chore(frontend): improve meta description

- docs/aprender-eosio/contratos-inteligentes.md
- docs/comunidad/enlaces-utiles.md
- docs/herramientas/ejemplos-contratos-inteligentes-eosio.md
- sidebars.js
- resolves #495
- resolves #500
1. Go to Aprender EOSIO / Contratos Inteligentes
2. Go to Comunidad / Enlaces utiles
> feat(frontend): Adding useful link ESP #495 #500

- docusaurus.config.js
- resolves [496](https://github.com/eoscostarica/guide.eoscostarica.io/issues/496)
1. The site build is still working
> refactor: remove unnecessary scripts

- docs/aprender-eosio/migracion-mandel.md
- resolves #issueNumber
1.
1.
1.
> fix(docs): adjust keywords

- docusaurus.config.js
- src/pages/index.js
- resolves #516
1. Go to homepage and click on switch theme
> fix(bug): Change to correct function ESP #516

- docusaurus.config.js
- resolves #465
1. Go to tools
2. Go to Readme
3. Reload the page
4. Check don't appear the slash
> fix(frontend): Adding command slash on config ESP #465

- docs/comunidad/redes-eosio.md
- resolves [#506](https://github.com/eoscostarica/guide.eoscostarica.io/issues/506)
- Also add loading lazy in the videos of the page
1. Go to community resources
1. Open Blockchain Networks or EOSIO Networks
1. Check the added line
> feat: add libre to eosio networks list

- package.json
- yarn.lock
- resolves  [#519](https://github.com/eoscostarica/guide.eoscostarica.io/issues/519)
1. Check the changed files
> feat: update docusaurus version #519

- docusaurus.config.js
> Optimize Page Title

- docs/herramientas/ejemplos-configuracion-nodeos.md
- docs/herramientas/ejemplos-contratos-inteligentes-eosio.md
- docs/herramientas/opciones-configuracion-nodeos.md
- resolves [#529](https://github.com/eoscostarica/guide.eoscostarica.io/issues/529)
- fix the wrong language in "configuración de nodeos" page
1. Check that the changed sidebar labels are correct
1. Check the translation in the `opciones-configuracion-nodeos.md` file
> Fix(frontend): adjust sidebar label 529

- docs/herramientas/plantilla-readme.md
- makes for an SEO friendly link to markdown source code page 
1. Go To https://guias.eoscostarica.io/docs/herramientas/plantilla-readme
1. See link
> Change link text to readme template source code

- CODE_OF_CONDUCT.md
- docs/boilerplate-para-aplicacion-web.md
- docs/plantilla-para-aplicacion-web.md
- docs/tutoriales/instalacion-de-red-privada.md
> replace eosio.cr domain with edenia.cloud

- docusaurus.config.js
- src/css/homepage.css
- src/pages/index.js
- resolves #544
1.Enter to homepage
> fix(frontend):Working without delay ESP #544

- docs/aprender-eosio/cadena-de-bloques-eos.md
- docs/aprender-eosio/contratos-inteligentes.md
- docs/aprender-eosio/cuentas-permisos.md
- docs/aprender-eosio/desarrollo-de-dapps.md
- docs/aprender-eosio/mecanismo-de-consenso.md
- docs/aprender-eosio/nft-en-eosio.mdx
- docs/aprender-eosio/seguridad-blockchain.md
- docs/aprender-eosio/uso-de-recursos.md
- docs/comunidad/redes-eosio.md
- docs/devops.md
- docs/herramientas-para-desarrolladores-ux-ui.md
- docs/herramientas-para-desarrolladores.md
- docs/interplanetary-file-system.md
- docs/mecanismos-de-consenso-blockchain.md
- docs/metodologia-vuelos.md
- docs/metodologias-agiles.md
- docs/pautas-para-codigo-abierto.md
- docs/proyectos-de-codigo-abierto.mdx
- docs/tutoriales/contrato-hola-mundo.md
- docs/tutoriales/cpp-moderno.md
- docs/tutoriales/guia-markdown.md
- docs/tutoriales/tutorial-flujo-trabajo-git.md
- docs/tutoriales/tutorial-react.md
- src/components/ProjectContainer/DisplayImages.js
- resolves #534 [Resolve errors in some Markdown files](https://github.com/eoscostarica/guide.eoscostarica.io/issues/534)
1.These changes are in the markdown but it can't see.
> fix(frontend): relsolve errors in markdown files

- package.json
- src/css/homepage.css
- src/theme/Footer/index.js
- src/theme/Footer/styles.module.css
- yarn.lock
- resolves #397  #393 and https://github.com/eoscostarica/guide.eoscostarica.io/issues/550
1. yarn build
2. npm run serve
> feat(frontend); fixed footer errors #397 #393

- docs/aprender-eosio/protocolo-eosio.md
- docusaurus.config.js
- package.json
- sidebars.js
- src/pages/index.js
- src/theme/Footer/index.js
- yarn.lock
- resolves #397 
- resolves #553
>  add antelope references

- src/pages/index.js
- src/theme/Footer/index.js
- resolves #400
1. go to footer and homepage and click on links
> fix(guides): fixed broken links

- package.json
- src/pages/index.js
- yarn.lock
> feat(package.json): updated docusarus version
